### ISSUE TITLE
[JENKINS-43439] Jenkins jobs build steps disappear after version upgrade to 2.46.1 due to the uninstalled Shared Objects plugin

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkinsci/envinject-plugin#586]
<p>This morning, after I upgraded the version to 2.46.1 (latest), all my job build steps become empty in the web UI, but I can still see the job config.xml has those configuration.  I also see this error message pop up “<b>You have data stored in an older format and/or unreadable data.) and all error messages contain this:</b></p>

<p> </p>

<p>ConversionException: org.jenkinsci.plugins.sharedobjects.SharedObjectJobProperty : org.jenkinsci.plugins.sharedobjects.SharedObjectJobProperty ---- Debugging information ---- message : org.jenkinsci.plugins.sharedobjects.SharedObjectJobProperty cause-exception : com.thoughtworks.xstream.mapper.CannotResolveClassException cause-message : org.jenkinsci.plugins.sharedobjects.SharedObjectJobProperty class : [Lorg.jenkinsci.plugins.envinject.model.EnvInjectJobPropertyContributor; required-type : [Lorg.jenkinsci.plugins.envinject.model.EnvInjectJobPropertyContributor; converter-type : com.thoughtworks.xstream.converters.collections.ArrayConverter path : /project/properties/EnvInjectJobProperty/contributors/org.jenkinsci.plugins.sharedobjects.SharedObjectJobProperty line number : 31 -------------------------------, MissingFieldException: No field 'org.jenkinsci.plugins.sharedobjects.ToolInstallationJobProperty' found in class 'org.jenkinsci.plugins.envinject.EnvInjectJobProperty'</p>

---
<details><summary><i>Originally reported by <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=monkeylittle">monkeylittle</a>, imported from: <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-43439" target="_blank">Jenkins jobs build steps disappear after version upgrade to 2.46.1 due to the uninstalled Shared Objects plugin</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Minor
<li><b>component(s)</b>: envinject-plugin
<li><b>label(s)</b>: xstream
<li><b>resolution</b>: Unresolved
<li><b>votes</b>: 0
<li><b>watchers</b>: 2
<li><b>imported</b>: 20251223-165436
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>This morning, after I upgraded the version to 2.46.1 (latest), all my job build steps become empty in the web UI, but I can still see the job config.xml has those configuration.  I also see this error message pop up “<b>You have data stored in an older format and/or unreadable data.) and all error messages contain this:</b></p>

<p> </p>

<p>ConversionException: org.jenkinsci.plugins.sharedobjects.SharedObjectJobProperty : org.jenkinsci.plugins.sharedobjects.SharedObjectJobProperty ---- Debugging information ---- message : org.jenkinsci.plugins.sharedobjects.SharedObjectJobProperty cause-exception : com.thoughtworks.xstream.mapper.CannotResolveClassException cause-message : org.jenkinsci.plugins.sharedobjects.SharedObjectJobProperty class : [Lorg.jenkinsci.plugins.envinject.model.EnvInjectJobPropertyContributor; required-type : [Lorg.jenkinsci.plugins.envinject.model.EnvInjectJobPropertyContributor; converter-type : com.thoughtworks.xstream.converters.collections.ArrayConverter path : /project/properties/EnvInjectJobProperty/contributors/org.jenkinsci.plugins.sharedobjects.SharedObjectJobProperty line number : 31 -------------------------------, MissingFieldException: No field 'org.jenkinsci.plugins.sharedobjects.ToolInstallationJobProperty' found in class 'org.jenkinsci.plugins.envinject.EnvInjectJobProperty'</p></pre>
</details>
</details>
<ul><li><i>environment</i>: <code>Linux</code></li></ul>
